theme: jekyll-theme-slate
title: Claudio Lucinda Personal Git Webpage
description: This is a webpage in which I make public my academic projects. Feel free to bookmark this page to keep an eye on my project updates.
